### ISSUE TITLE
Generating abstract class tests only outputs setUp, tearDown & 1 line unit tests

### ISSUE THREAD

**Issue by Manardson** [paul-thebaud/phpunitgen-webapp#36] opened 2021-09-22 15:41 UTC
Hi, it's a great tool this phpunit generator and allows people to learn more about unit tests, thank you for that!

I read through the documentation and tried all the settings in the config on https://phpunitgen.io/tool web page, but sadly on an abstract class which is not a controller I wasn't able to generate more than setUp() and tearDown() with usable code in them even while I had "Automatic generation" enabled. The class itself has 8 public functions, about 250 lines of code and all generated tests had 1 line of code in them stating "$this->markTestIncomplete();"

Is this the intended behaviour or am I doing something wrong?

Kind thanks!

**Comment by paul-thebaud** [comment] 2021-09-22 18:53
Hi, thanks a lot!
As stated inside [the README key features section](https://github.com/paul-thebaud/phpunitgen-webapp#key-features):

>PhpUnitGen is not meant to generate your tests content but only the skeleton (except for getters/setters).
>
>This is because inspecting your code to generate the appropriate test is way too complex, and might result in missing some of the code's features or marking them as "passed unit test" even if it contains errors.

I'm closing this issue as this is the intended behavior. If you have any other issues, feel free to reopen or create a new issue :)

**Closed by paul-thebaud** 2021-09-22 18:53 UTC
